<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BoilerAppMessenger\Factory\InlineStyleProcessorFactory'                   => __DIR__ . '/src/BoilerAppMessenger/Factory/InlineStyleProcessorFactory.php',
    'BoilerAppMessenger\Factory\MessengerServiceFactory'                       => __DIR__ . '/src/BoilerAppMessenger/Factory/MessengerServiceFactory.php',
    'BoilerAppMessenger\Factory\StyleInlinerFactory'                           => __DIR__ . '/src/BoilerAppMessenger/Factory/StyleInlinerFactory.php',
    'BoilerAppMessenger\Factory\Transport\FileTransportFactory'                => __DIR__ . '/src/BoilerAppMessenger/Factory/Transport/FileFactory.php',
    'BoilerAppMessenger\Factory\Transport\SendmailTransportFactory'            => __DIR__ . '/src/BoilerAppMessenger/Factory/Transport/SendmailFactory.php',
    'BoilerAppMessenger\Factory\Transport\SmtpTransportFactory'                => __DIR__ . '/src/BoilerAppMessenger/Factory/Transport/SmtpFactory.php',
    'BoilerAppMessenger\Mail\Message'                                          => __DIR__ . '/src/BoilerAppMessenger/Mail/Message.php',
    'BoilerAppMessenger\Mail\Transport\AttachementsAwareTrait'                 => __DIR__ . '/src/BoilerAppMessenger/Mail/Transport/AttachementsAwareTrait.php',
    'BoilerAppMessenger\Mail\Transport\File'                                   => __DIR__ . '/src/BoilerAppMessenger/Mail/Transport/File.php',
    'BoilerAppMessenger\Mail\Transport\Sendmail'                               => __DIR__ . '/src/BoilerAppMessenger/Mail/Transport/Sendmail.php',
    'BoilerAppMessenger\Mail\Transport\Smtp'                                   => __DIR__ . '/src/BoilerAppMessenger/Mail/Transport/Smtp.php',
    'BoilerAppMessenger\Message'                                               => __DIR__ . '/src/BoilerAppMessenger/Message.php',
    'BoilerAppMessenger\Service\MessengerOptions'                              => __DIR__ . '/src/BoilerAppMessenger/Service/MessengerOptions.php',
    'BoilerAppMessenger\Service\MessengerService'                              => __DIR__ . '/src/BoilerAppMessenger/Service/MessengerService.php',
    'BoilerAppMessenger\StyleInliner\Processor\InlineStyleProcessor'           => __DIR__ . '/src/BoilerAppMessenger/StyleInliner/Processor/InlineStyleProcessor.php',
    'BoilerAppMessenger\StyleInliner\Processor\StyleInlinerProcessorInterface' => __DIR__ . '/src/BoilerAppMessenger/StyleInliner/Processor/StyleInlinerProcessorInterface.php',
    'BoilerAppMessenger\StyleInliner\StyleInlinerOptions'                      => __DIR__ . '/src/BoilerAppMessenger/StyleInliner/StyleInlinerOptions.php',
    'BoilerAppMessenger\StyleInliner\StyleInlinerService'                      => __DIR__ . '/src/BoilerAppMessenger/StyleInliner/StyleInlinerService.php',
    'BoilerAppMessenger\View\Renderer\EmailRenderer'                           => __DIR__ . '/src/BoilerAppMessenger/View/Renderer/EmailRenderer.php',
);